export const ACTIONS = {
    ITEMS_HAVE_ERROR:'ITEMS_HAVE_ERROR',
    ERROR_MESSAGE:'ERROR_MESSAGE',
    ITEMS_LOADING:'ITEMS_ARE_LOADING',
    CURRENCY_FETCH_DATA_SUCCESS:'CURRENCY_FETCH_DATA_SUCCESS',
    CURRENCY_SELECTED:"CURRENCY_SELECTED",
    SET_BASE_CURRENCY:"SET_BASE_CURRENCY",
    GET_RATES:"GET_RATES",

}
